name 'ericsson-tacacsplus'
version '0.1.0'
source 'git://github.com/Ericsson/puppet-module-tacacsplus.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Manage tacacsplus'
description 'Manage tacacsplus'
project_page 'https://github.com/Ericsson/puppet-module-tacacsplus'

dependency 'puppetlabs/stdlib', '3.2.x'
